Twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name='home'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.postspage, name='home'),
    path('create', views.create_post, name='create'),
    path('answer/<slug>', views.answer_, name='answer'),
    path('delete/<slug>', views.deletepost, name='delete'),
    path('<slug>', views.post_detail, name='post_detail')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('profile/<slug>', views.profile, name='profile'),
    path('follow/<slug>', views.follow_view, name='follow')
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    auth_slug = models.SlugField(default=None)
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.slug

    def editedbody(self):
        if len(self.body) > 120:
            return self.body[:120] + '  ...'
        else:
            return self.body


class Answer(models.Model):
    answer = models.TextField()
    target = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='target')
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')

    def __str__(self):
        return self.answer[:10]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    name = models.CharField(max_length=150)
    # bio = models.CharField(max_length=250)
    user_slug = models.SlugField(default=None)

    def __str__(self):
        return str(self.name)


class Follow(models.Model):
    me = models.OneToOneField(User, on_delete=models.CASCADE, related_name="me")
    other_guy = models.ManyToManyField(User, blank=True, related_name='other_guy')
    follower_slug = models.SlugField(default=str(me).strip())

    def __str__(self):
        return str(self.me)

posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta():
        model = models.Post
        fields = ['title', 'body']


class Answer(forms.ModelForm):
    class Meta():
        model = models.Answer
        fields = ['answer']

users/forms.py
from django import forms
from . import models


class CreateProfile(forms.ModelForm):
    class Meta():
        model = models.Profile
        fields = []


class Follow_form(forms.ModelForm):
    class Meta():
        model = models.Follow
        fields = []

Twitter/views.py
from django.shortcuts import render
from users.models import Follow, Profile
from posts.models import Post
from django.contrib.auth.decorators import login_required


@login_required(login_url='/users/login')
def HomePage(request):
    me = Follow.objects.get(follower_slug=request.user)
    my_name = Profile.objects.get(name=request.user)
    followings = me.other_guy.all
    posts = Post.objects.all()
    return render(request, 'home.html', {'followings': followings, 'posts': posts, 'my_name': my_name})

posts/views.py
from django.shortcuts import render, redirect
from . import models, forms
from django.contrib.auth.decorators import login_required
from users import models as m
from django.http import HttpResponse


@login_required(login_url='/users/login')
def postspage(request):
    posts = models.Post.objects.all()
    return render(request, 'posts_page.html', {'posts': posts})


@login_required(login_url='/users/login')
def post_detail(request, slug):
    post = models.Post.objects.get(slug=slug)
    answers = models.Answer.objects.all()
    return render(request, 'post_detail.html', {'post': post, 'answers': answers})


@login_required(login_url='/users/login')
def create_post(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST)
        instance = form.save(commit=False)
        instance.author = request.user
        number = 1
        instance.slug = instance.title.strip()
        while models.Post.objects.filter(slug=instance.slug):
            instance.slug = instance.title.strip() + str(number)
            number += 1
        instance.auth_slug = str(instance.author).strip()
        instance.save()
        return redirect('posts:home')
    form = forms.CreatePost
    return render(request, 'create_post.html', {'form': form})


@login_required(login_url='/users/login')
def answer_(request, slug):
    if request.method == 'POST':
        form = forms.Answer(request.POST)
        instance = form.save(commit=False)
        instance.target = models.Post.objects.get(slug=slug)
        instance.commenter = request.user
        instance.save()
        return redirect('posts:post_detail', slug=slug)
    form = forms.Answer
    return render(request, 'answer_page.html', {'form': form, 'slug': slug})


@login_required(login_url='/users/login')
def deletepost(request, slug):
    me = m.Profile.objects.get(name=request.user).name
    post = models.Post.objects.get(slug=slug)
    if str(post.author) == me:
        post.delete()
    return redirect('posts:home')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from posts.models import Post
from .models import Profile, Follow
from .forms import CreateProfile, Follow_form
from django.contrib.auth.decorators import login_required


@login_required(login_url='/users/login')
def users(request):
    return render(request, 'usersPage.html')


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        form2 = CreateProfile(request.POST)
        form3 = Follow_form(request.POST)
        if form.is_valid():
            user = form.save()
            instance = form2.save(commit=False)
            instance2 = form3.save(commit=False)
            instance.name = str(user.username)
            instance.user_slug = str(instance.name).strip()
            instance.save()
            instance2.me = user
            instance2.follower_slug = str(instance2.me).strip()
            instance2.save()
            login(request, user)
            follow_view(request, 'sinarayo')
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


@login_required(login_url='/users/login')
def profile(request, slug):
    posts = Post.objects.all()
    form = Profile.objects.get(user_slug=slug)
    our_name = str(Profile.objects.get(name=request.user))

    other_user = Follow.objects.get(follower_slug=slug)
    me = Follow.objects.get(follower_slug=request.user)
    if me.other_guy.filter(me=other_user).exists():
        is_following = True
    else:
        is_following = False

    return render(request, 'profile.html',
                  {'form': form, 'posts': posts, 'our_name': our_name, 'is_following': is_following})


@login_required(login_url='/users/login')
def follow_view(request, slug):
    other_user = Follow.objects.get(follower_slug=slug)  # in esme kasi ke gharare folow she ro barmigardoone(following)
    me = Follow.objects.get(follower_slug=request.user)  # in esme hesabe ma ro barmigardoone (follower)
    if me.me != other_user.me:
        if me.other_guy.filter(me=other_user).exists():
            if slug == 'sinarayo':
                return redirect('users:profile', slug=slug)
            me.other_guy.remove(other_user.me)
            Follow.is_following = False
            return redirect('users:profile', slug=slug)
        else:
            me.other_guy.add(other_user.me)
            Follow.is_following = True
            return redirect('users:profile', slug=slug)

    return redirect('users:profile', slug=slug)

posts/templates/answer_page.html
{% extends 'base.html' %}

{% block title %}
    answer
{% endblock %}
{% block body %}
    <h1>comment your idea</h1>
    <form class="site-form" action="{% url 'posts:answer' slug=slug %}" method="post">
    {{ form }}
    {% csrf_token %}
    <input type="submit" value="Go" class="input1">
    </form>
{% endblock %}

posts/templates/create_post.html
{% extends 'base.html' %}
{% block title %}
CreatePost
{% endblock %}

{% block body %}
    <form class="site-form" action="{% url 'posts:create' %}" method="post">
    {{ form }}
    {% csrf_token %}
    <input type="submit" value="Create" class="input1">
    </form>
{% endblock %}

posts/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}
    postDetail
{% endblock %}
{% block body %}
    <h1>{{ post.title }}</h1>
    <p class="post-body">{{ post.body }}</p>
    <div class="detail"><p class="seller"> author : <a href="{% url 'users:profile' slug=post.auth_slug %}" class="author-link">{{post.author}}</a></p></div>
    <p class="datetime">{{ post.date }}</p>

<div class="space"></div>

{#    <h2 class="comments_text">Comments</h2>#}
    {% for answer in answers %}
    {% if answer.target == post %}
    <div class="comments_box">
    {% endif %}
    {% endfor %}

    {% for answer in answers %}
    {% if answer.target == post %}
        <li class="answer_list"><p class="answer">{{ answer.answer }}</p>
        <a href="{% url 'users:profile' slug=answer.commenter %}"><h3 class="answer_commenter">{{ answer.commenter }}</h3></a></li>
    {% endif %}
    {% endfor %}

    <h2 class="comment_btn"><a href="{% url 'posts:answer' slug=post.slug %}">Comment</a></h2>
{% endblock %}

posts/templates/posts_page.html
{% extends 'base.html' %}

{% block title %}
    postsPage
{% endblock %}
{% block body %}
    <p><a href="{% url 'posts:create' %}"  class="highlight"> Create new Post </a></p>
    {% for post in posts %}
    <div class="article">
    <h2 class="post_title"><a href= "{% url 'posts:post_detail' slug=post.slug %}"> {{ post.title }} </a></h2>
    <p class="editedbody"> {{ post.editedbody }} </p>
    <p class="seller">added by <a href="{% url 'users:profile' slug=post.auth_slug%}" class="author-link">{{post.author.username}}</a></p>
    </div>
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
 <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>

<div class="wrapper">

    <h1><a href="{% url 'home' %}" class="highlight3">HOME</a> </h1>

<body>
{% block body %}
{% endblock %}
</body>
</div>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
HomePage
    </title>
 <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>

<div class="wrapper">

<body>
    <h1>Welcome to my twitter</h1>
    <p><a href="{% url 'users:users' %}"> manage your account</a></p>
    <div class="detail"><p class="seller"><a href="{% url 'users:profile' slug=my_name.user_slug %}" class="author-link">Your Profile</a></p></div>
    <h2 class="post-page-link"><a href="{% url 'posts:home' %}">Visit all posts</a></h2>
    <p><a href="{% url 'posts:create' %}" class="highlight"> Create new Post </a></p>

    <h2 class="your_following">your following posts</h2>

    {% for post in posts %}
    {% if post.author in followings %}
    <div class="article">
    <h2 class="post_title"><a href= "{% url 'posts:post_detail' slug=post.slug %}"> {{ post.title }} </a></h2>
    <p class="editedbody"> {{ post.editedbody }} </p>
    <p class="seller">added by <a href="{% url 'users:profile' slug=post.auth_slug%}" class="author-link">{{post.author.username}}</a></p>

{#    answers    #}
    </div>

    {% endif %}
    {% endfor %}

</body>
</div>
</html>

users/templates/login.html
{% extends 'base.html' %}
{% block title %}
    LogIn
{% endblock %}
{% block body %}
    <h1>Login</h1>
<form class="site-form" method="post" action="{% url 'users:login' %}">
    {{ form }}
    {% csrf_token %}
    {% if request.GET.next %}
        <input name="next" type="hidden" value="{{ request.GET.next }}">
        {% endif %}
    <input type="submit" value="Log Me In" class="input1">

<div class="signup_request"><p>dont have any account? <a href="{% url 'users:signup' %}">create one</a></p></div>
</form>

{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    ProfilePage
{% endblock %}

{% block body %}
    <h1 class="profile_name">///&nbsp;&nbsp;&nbsp; {{ form.name }} &nbsp;&nbsp;&nbsp; ///</h1>
    {% if our_name != form.name and form.name != 'sinarayo' %}
        {% if is_following == False %}
            <a href="{% url "users:follow" slug=form.name %}" class="follow_btn">Follow</a>
        {% elif is_following == True %}
            <a href="{% url "users:follow" slug=form.name %}" class="Unfollow_btn">unFollow</a>
        {% endif %}

    {% elif our_name == form.name %}
        <h1 class="follow_btn">Your Profile</h1>
    {% elif form.name == 'sinarayo' %}
        <h1 class="follow_btn">Admin</h1>
    {% endif %}
    <h1>Posts</h1>
    {% for post in posts %}
        {% if post.author.username == form.name %}
            <div class="article">
                <h2 class="post_title"><a href="{% url 'posts:post_detail' slug=post.slug %}"> {{ post.title }} </a>
                </h2>
                <p class="editedbody"> {{ post.editedbody }} </p>
             {% if post.author.username == our_name %}
                <p><a href="{% url 'posts:delete' slug=post.slug %}">delete post</a></p>
             {% endif %}
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}
{% block title %}
    SignUp
{% endblock %}
{% block body %}
    <h1>Sign Up</h1>
<form class="site-form" method="post" action="{% url 'users:signup' %}">
    {{ form }}
    {% csrf_token %}
    <input type="submit" value="Sign Me Up" class="input1">
<div class="signup_request"><p>already have an account? <a href="{% url 'users:login' %}">login</a></p></div>
</form>

{% endblock %}

users/templates/usersPage.html
{% extends 'base.html' %}

{% block title %}
UsersPage
{% endblock %}
{% block body %}
    <nav>
    <ul>
        <li>
            <form class="logout-list" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
        </li>
    </ul>
</nav>


<h2><a href="{% url 'users:signup' %}"> Create Your account </a></h2>

<p> Do you have one? </p>
<h2><a href="{% url 'users:login' %}">Log in</a></h2>
{% endblock %}